CREATE TABLE VENDOR
( VendorID CHAR(2) NOT NULL, 
 VendorName VARCHAR(25) NOT NULL, 
 PRIMARY KEY (VendorID) ); 

CREATE TABLE CATEGORY 
( CategoryID CHAR(2) NOT NULL, 
 CategoryName VARCHAR(25) NOT NULL, 
 PRIMARY KEY (CategoryID) ); 

CREATE TABLE PRODUCT 
( ProductID CHAR(6) NOT NULL, 
 ProductName VARCHAR(25) NOT NULL, 
ProductPrice NUMERIC (7,2) NOT NULL, 
VendorID CHAR(2) NOT NULL, 
CategoryID CHAR(2) NOT NULL, 
 PRIMARY KEY (ProductID), 
FOREIGN KEY (VendorID) REFERENCES VENDOR(VendorID), 
FOREIGN KEY (CategoryID) REFERENCES 
 CATEGORY(CategoryID) ); 



CREATE TABLE REGION 
( RegionID CHAR NOT NULL, 
 RegionName VARCHAR(25) NOT NULL, 
 PRIMARY KEY (RegionID) ); 


CREATE TABLE STORE 
( StoreID VARCHAR(3) NOT NULL, 
 StoreZip CHAR(5) NOT NULL, 
 RegionID CHAR NOT NULL, 
 PRIMARY KEY (StoreID), 
FOREIGN KEY (RegionID) REFERENCES REGION(RegionID) ); 


CREATE TABLE CUSTOMER 
( CustomerID CHAR(7) NOT NULL, 
CustomerName VARCHAR(15) NOT NULL, 
 CustomerZip CHAR(5) NOT NULL, 
 PRIMARY KEY (CustomerID) ); 


CREATE TABLE SALESTRANSACTION 
( TID VARCHAR(8) NOT NULL, 
 CustomerID CHAR(7) NOT NULL, 
 StoreID VARCHAR(3) NOT NULL, 
tdate DATE NOT NULL, 
 PRIMARY KEY (TID), 
FOREIGN KEY (CustomerID) REFERENCES 
 CUSTOMER(CustomerID), 
FOREIGN KEY (StoreID) REFERENCES STORE(StoreID));


CREATE TABLE INCLUDES 
( ProductID CHAR(6) NOT NULL, 
 TID VARCHAR(8) NOT NULL, 
 Quantity INT NOT NULL, 
 PRIMARY KEY (ProductID, TID), 
FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID), 
FOREIGN KEY (TID) REFERENCES SALESTRANSACTION(TID) );